name: Main
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
jobs: 
  # Checks the code
  test_analyze_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21.0'
      - name: Install dependencies
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run tests
        run: go test ./...
      - name: Analyze Code with go vet
        run: go vet ./...
      - name: Run staticcheck
        run: staticcheck ./...
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21.0'
      - name: Fuzz Parse
        run: "go test -fuzz=FuzzParser_Parse$ -fuzztime=30s"
      - name: Fuzz ParseNumber
        run: "go test -fuzz=FuzzParser_ParseNumber$ -fuzztime=30s"
  lint:
    runs-on: ubuntu-latest
    image: golangci/golangci-lint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Lint
        run: golangci-lint run
      
